package:
  name: maven
  version: 3.2.1

source:
  fn: apache-maven-3.2.1-bin.zip
  url: http://mirror.sdunix.com/apache/maven/maven-3/3.2.1/binaries/apache-maven-3.2.1-bin.zip
  md5: 5d86506f17e5ff0b0c83c648f4093abb

build:
  number: 1

about:
    home: http://maven.apache.org
    license:  Apache License 2.0
