package:
  name: expat
  version: 2.1.0

source:
  fn: expat-2.1.0.tar.gz
  url: http://downloads.sourceforge.net/expat/expat-2.1.0.tar.gz
  md5: dd7dab7a5fea97d2a6a43f511449b7cd

build:
  number: 1

about:
    home: http://expat.sourceforge.net/
    license: MIT
